# base_url = "https://blog.etheve.eu"
base_url = "http://localhost:8111"
title = "Guileas blog"
default_language = "en"
highlight_code = true
highlight_theme = "one-dark"
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
	{ name = "categories", feed = true, paginate_by = 10 },
	{ name = "tags", fees = true, paginate_by = 10 },
]
languages = [
	{code="fr"},
]
compile_sass = true
build_search_index = true
ignored_content = []
extra_syntaxes = []

[link_checker]
skip_prefixes = ["http://[2001:db8::]/"]
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[translations]

[extra]
navbar_items = [
	{code = "en", nav_items = [
		{ url = "/", name = "Home" },
		{ url = "/posts", name = "Posts" },
		{ url = "/docs", name = "Docs" },
		{ url = "/tags", name = "Tags" },
		{ url = "/categories", name = "Categories" }
	]},
	{ code = "fr", nav_items = [
		{ url = "/", name = "Accueil" },
		{ url = "/posts", name = "Posts" },
	]}
	
]

[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.author]
name = "Guileas"
avatar = "/images/avatar.png"

[extra.social]
github = "Guileas"
gitlab = "guileas"
linkedin = "gwenolaetheve"
stackoverflow = "14186891"

[extra.analytics]
google = ""

[extra.commenting]
hyvor = ""

[extra.mapbox]
access_token = ""
